### ISSUE TITLE
Implement interfaces instead of hard coded services. 

### ISSUE THREAD

**Issue by dipeshdulal** [dipeshdulal/clean-gin#10]

**Comment by peterwillcn** [comment]
any news

**Comment by dipeshdulal** [comment]
Been extremely busy with other things. We have been revamping this architecture a bit following standard project structure of go project at @wesionaryTeam using interfaces as well. 

Once I will be a bit free I can work on this based on the approach we use at wesionaryteam. But can't give a actual timeline. Sorry for that 🙇‍♂️

**Comment by peterwillcn** [comment]
Looking forward to it. Thank you.
