### ISSUE TITLE
Unify logger

### ISSUE THREAD

**Issue by tienthanh2509** [dipeshdulal/clean-gin#27]
Thank for the great template, but a bit inconsistent with the logger, each module has use it own logger instead of `lib.Logger`

- main app: zap
- gorm: gorm logger
- fx and viper may be unable to use the same logger

So can you make the gorm use `lib.Logger` for this template?

**Comment by dipeshdulal** [comment]
Thank you for the feedback. :bow: 
Sure we can. 🚀
