### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by Cull-Methi** [dipeshdulal/clean-gin#31]
Hey all, wanted to reach out regarding a license for this template.

Currently, with no license it's by default "All right reserved" see https://github.com/sveltejs/template/issues/78 and https://github.com/sveltejs/template/pull/201 for more info on a similar situation - project with a public template on github and no license. Copy pasting from Svelte issue #78:

> From the [GitHub guidance on licensing](https://help.github.com/en/articles/licensing-a-repository):
>>    You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. [The Open Source Guide](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) provides additional guidance on choosing the correct license for your project.

If you don't want to restrict things you can Use the 0BSD license - https://opensource.org/licenses/0BSD, alternatively you can go the path of Gorm and Gin, which both use the MIT license - https://opensource.org/licenses/MIT. These are just suggestions, of course, and the decision is ultimately up to you

Created https://github.com/dipeshdulal/clean-gin/pull/32 for 0BSD and https://github.com/dipeshdulal/clean-gin/pull/33 for MIT License. Feel free to merge either of them if you like those choices

**Comment by dipeshdulal** [comment]
Thank You. 🙇
