### ISSUE TITLE
Logger LOG_LEVEL is ignored

### ISSUE THREAD

**Issue by dsmackie** [dipeshdulal/clean-gin#43]
The `newLogger` function `env` parameter is never used. This results in the `LOG_LEVEL` from config never being applied.

Default logging level always remains set to `zap.PanicLevel`

https://github.com/dipeshdulal/clean-gin/blob/2a5bbb3c3775eb2a1d0ea9f06ad05cc437e28bdc/lib/logger.go#L155

https://github.com/dipeshdulal/clean-gin/blob/2a5bbb3c3775eb2a1d0ea9f06ad05cc437e28bdc/lib/logger.go#L169

**Comment by dipeshdulal** [comment]
Closed after merging. #44
