### ISSUE TITLE
support for RBAC?

### ISSUE THREAD

**Issue by ngxlua** [dipeshdulal/clean-gin#7]
I see that https://github.com/casbin/casbin supports user rights management very much, can you support it?

Using gin + gorm + casbin + ... to build a more perfect template

Thank you, author.

**Comment by dipeshdulal** [comment]
@ngxlua It is the first time I am seeing this open source project. It would be awesome addition to the template. 
If I have some time I will try to R&D the project and implement if possible. 

PR's are also welcome. 🙇

**Comment by ngxlua** [comment]
> @ngxlua It is the first time I am seeing this open source project. It would be awesome addition to the template.
> If I have some time I will try to R&D the project and implement if possible.
> 
> PR's are also welcome. bow

Thank you for your reply. I have learned a lot from the design of clean-gin.

I'm not good at back-end program development, but when needed, I can develop front-end management pages for clean-gin, using react or vue.

**Comment by dipeshdulal** [comment]
Glad it helped. 🙇  
Closing this issue for now. Will try to R&D and implement RBAC later on.
